// Fase 34.x: curadoria de videos do YouTube pro catalogo de exercicios --
// atualizacao em lote pontual (mesmo padrao de seed-featured-exercises.ts),
// nao faz parte do db:seed automatico. Idempotente: os updates sao
// absolutos por nome, pode rodar de novo sem efeito colateral.
//
// Casamento por NAME (nao por id): os ids sao gerados independentemente em
// cada ambiente (dev/producao tem UUIDs diferentes pro mesmo exercicio
// seedado), entao usar id quebraria o update em producao. Nomes do
// catalogo sao unicos (confirmado antes de gerar este arquivo).
import prisma from "../src/lib/prisma";

const EXERCISE_VIDEOS: Array<{ name: string; youtubeUrl: string }> = [
  {name:"Prancha Isométrica",youtubeUrl:"https://www.youtube.com/watch?v=pSHjTRCQxIw"},
  {name:"Remada Curvada com Barra",youtubeUrl:"https://www.youtube.com/watch?v=vT2GjY_Umpw"},
  {name:"Abdominal Bicicleta",youtubeUrl:"https://www.youtube.com/watch?v=h313Yleb-ek"},
  {name:"Cadeira Adutora",youtubeUrl:"https://www.youtube.com/watch?v=ZZp5_OS_sTA"},
  {name:"Mountain Climbers",youtubeUrl:"https://www.youtube.com/watch?v=KLTY9yjk7jE"},
  {name:"Remada Alta com Barra",youtubeUrl:"https://www.youtube.com/watch?v=GKvpKkbMWtw"},
  {name:"Remada Alta no Cabo",youtubeUrl:"https://www.youtube.com/watch?v=qFyRN_dIBi4"},
  {name:"Agachamento Búlgaro",youtubeUrl:"https://www.youtube.com/watch?v=p_qNZJ50iO8"},
  {name:"Rosca Direta com Halteres",youtubeUrl:"https://www.youtube.com/watch?v=w9_ggo0_34k"},
  {name:"Desenvolvimento na Máquina",youtubeUrl:"https://www.youtube.com/watch?v=Q7K6DI9R-A8"},
  {name:"Hiperextensão Lombar",youtubeUrl:"https://www.youtube.com/watch?v=6Bg5woPBEA8"},
  {name:"Encolhimento no Cabo",youtubeUrl:"https://www.youtube.com/watch?v=EllUwusDzCM"},
  {name:"Elevação Frontal com Barra",youtubeUrl:"https://www.youtube.com/watch?v=Tf2JOnjjPko"},
  {name:"Desenvolvimento com Halteres",youtubeUrl:"https://www.youtube.com/watch?v=qEwKCR5JCog"},
  {name:"Abdominal Supra no Solo",youtubeUrl:"https://www.youtube.com/watch?v=jDwoBqPH0jk"},
  {name:"Alongamento de Tríceps Overhead",youtubeUrl:"https://www.youtube.com/watch?v=T4KOPrmWYV8"},
  {name:"Rosca Scott com Barra",youtubeUrl:"https://www.youtube.com/watch?v=FxrrSYi9nks"},
  {name:"Remada Baixa no Cabo",youtubeUrl:"https://www.youtube.com/watch?v=GZbfZ033f74"},
  {name:"Supino Reto com Halteres",youtubeUrl:"https://www.youtube.com/watch?v=P2xVkheMBZM"},
  {name:"Flexão de Braço",youtubeUrl:"https://www.youtube.com/watch?v=IZL63x3I6lg"},
  {name:"Puxada Frontal na Polia",youtubeUrl:"https://www.youtube.com/watch?v=CAwf7n6Luuc"},
  {name:"Rosca Concentrada no Cabo",youtubeUrl:"https://www.youtube.com/watch?v=JxPGtPFxvJc"},
  {name:"Levantamento Terra Sumô",youtubeUrl:"https://www.youtube.com/watch?v=kLWW-mxUT-w"},
  {name:"Remada na Máquina",youtubeUrl:"https://www.youtube.com/watch?v=Q5JEP3hg-Xc"},
  {name:"Alongamento Borboleta (Adutores)",youtubeUrl:"https://www.youtube.com/watch?v=NAVJBV_05JU"},
  {name:"Elevação Frontal com Halteres",youtubeUrl:"https://www.youtube.com/watch?v=sxeqiszaWao"},
  {name:"Panturrilha em Pé",youtubeUrl:"https://www.youtube.com/watch?v=-M4-G8p8fmc"},
  {name:"Barra Fixa Supinada",youtubeUrl:"https://www.youtube.com/watch?v=en71b8Yy8FQ"},
  {name:"Extensão de Tríceps Unilateral no Cabo",youtubeUrl:"https://www.youtube.com/watch?v=lIvLkJI2-ZU"},
  {name:"Levantamento Terra",youtubeUrl:"https://www.youtube.com/watch?v=1ZXobu7JvvE"},
  {name:"Agachamento com Peso Corporal",youtubeUrl:"https://www.youtube.com/watch?v=etz4vJAVMa4"},
  {name:"Encolhimento com Barra",youtubeUrl:"https://www.youtube.com/watch?v=6B-iBgzBHQ0"},
  {name:"Crucifixo na Máquina Voador",youtubeUrl:"https://www.youtube.com/watch?v=Hs5Gn65_P0g"},
  {name:"Panturrilha Sentado",youtubeUrl:"https://www.youtube.com/watch?v=3afDSh_V0sg"},
  {name:"Remo Ergométrico",youtubeUrl:"https://www.youtube.com/watch?v=UtK0CwVxhLE"},
  {name:"Elevação Lateral no Cabo",youtubeUrl:"https://www.youtube.com/watch?v=9zh-c9JQN9k"},
  {name:"Rosca Alternada com Halteres",youtubeUrl:"https://www.youtube.com/watch?v=sAq_ocpRh_I"},
  {name:"Cadeira Extensora",youtubeUrl:"https://www.youtube.com/watch?v=YyvSfVjQeL0"},
  {name:"Agachamento na Máquina Smith",youtubeUrl:"https://www.youtube.com/watch?v=KDUQ7pTTXhM"},
  {name:"Bicicleta Ergométrica",youtubeUrl:"https://www.youtube.com/watch?v=szAdFvQZXtI"},
  {name:"Pular Corda",youtubeUrl:"https://www.youtube.com/watch?v=bB2BMeZTygg"},
  {name:"Elevação Pélvica com Barra",youtubeUrl:"https://www.youtube.com/watch?v=xDmFkJxPzeM"},
  {name:"Supino Máquina",youtubeUrl:"https://www.youtube.com/watch?v=YIwYL1DjXzo"},
  {name:"Panturrilha em Pé com Halteres",youtubeUrl:"https://www.youtube.com/watch?v=59HKuN7WRjI"},
  {name:"Elevação em Y no Banco Inclinado",youtubeUrl:"https://www.youtube.com/watch?v=U1oifcjJhNU"},
  {name:"Prancha com Deslize",youtubeUrl:"https://www.youtube.com/watch?v=P6I_e5fnOb4"},
  {name:"Remada Unilateral com Halter",youtubeUrl:"https://www.youtube.com/watch?v=K25eTWoEOWU"},
  {name:"Avanço Estático com Halteres",youtubeUrl:"https://www.youtube.com/watch?v=8kjP-ZB_z_8"},
  {name:"Elevação de Joelhos Suspenso",youtubeUrl:"https://www.youtube.com/watch?v=crMmq9UwiHo"},
  {name:"Elíptico",youtubeUrl:"https://www.youtube.com/watch?v=KjoCtuZfew4"},
  {name:"Tríceps na Máquina",youtubeUrl:"https://www.youtube.com/watch?v=bd_VvOCpdKM"},
  {name:"Remada Cavalinho",youtubeUrl:"https://www.youtube.com/watch?v=5xdW-J6MRKE"},
  {name:"Rosca Spider",youtubeUrl:"https://www.youtube.com/watch?v=NFILNmHcdl0"},
  {name:"Prancha Lateral",youtubeUrl:"https://www.youtube.com/watch?v=oSInFXYwp3k"},
  {name:"Stiff com Halteres",youtubeUrl:"https://www.youtube.com/watch?v=oXwLyXxYNfY"},
  {name:"Elevação de Pernas no Banco",youtubeUrl:"https://www.youtube.com/watch?v=knoCsKDwuKc"},
  {name:"Mergulho no Banco",youtubeUrl:"https://www.youtube.com/watch?v=6kALZikXxLc"},
  {name:"Abdominal Oblíquo no Solo",youtubeUrl:"https://www.youtube.com/watch?v=j5dAikcZwq0"},
  {name:"Abdominal Declinado",youtubeUrl:"https://www.youtube.com/watch?v=V4DOUirrM1g"},
  {name:"Tríceps Francês na Polia",youtubeUrl:"https://www.youtube.com/watch?v=7lFerVpvCeI"},
  {name:"Mergulho nas Paralelas",youtubeUrl:"https://www.youtube.com/watch?v=OPyI6B68tHw"},
  {name:"Elevação Lateral na Máquina",youtubeUrl:"https://www.youtube.com/watch?v=8GvYpmAL4zA"},
  {name:"Agachamento Livre",youtubeUrl:"https://www.youtube.com/watch?v=ultWZbUMPL8"},
  {name:"Stiff com Barra",youtubeUrl:"https://www.youtube.com/watch?v=t4KS5hvhT88"},
  {name:"Supino Reto na Máquina Smith",youtubeUrl:"https://www.youtube.com/watch?v=czKoUYNARdI"},
  {name:"Rosca Inversa com Barra",youtubeUrl:"https://www.youtube.com/watch?v=nz_pX38WFZE"},
  {name:"Alongamento do Piriforme Sentado",youtubeUrl:"https://www.youtube.com/watch?v=OHa2E6gB-oQ"},
  {name:"Barra Fixa Pronada",youtubeUrl:"https://www.youtube.com/watch?v=JwrlkCMysRU"},
  {name:"Elevação Lateral com Halteres",youtubeUrl:"https://www.youtube.com/watch?v=3VcKaXpzqRo"},
  {name:"Mesa Flexora",youtubeUrl:"https://www.youtube.com/watch?v=1Tq3QdYUuHs"},
  {name:"Prancha com Elevação de Braço",youtubeUrl:"https://www.youtube.com/watch?v=ZzEeLIrTMes"},
  {name:"Remada Invertida na Barra",youtubeUrl:"https://www.youtube.com/watch?v=Dn4LAgKA360"},
  {name:"Elevação de Pernas na Barra Fixa",youtubeUrl:"https://www.youtube.com/watch?v=JB2oyawG9KI"},
  {name:"Flexão Fechada",youtubeUrl:"https://www.youtube.com/watch?v=tJYty14Y8i0"},
  {name:"Alongamento de Quadríceps em Pé",youtubeUrl:"https://www.youtube.com/watch?v=n1nEL1KmpOA"},
  {name:"Escada Ergométrica (StepMill)",youtubeUrl:"https://www.youtube.com/watch?v=nal_FtVy8yk"},
  {name:"Rotação Russa (Russian Twist)",youtubeUrl:"https://www.youtube.com/watch?v=sTPoBs5gKUk"},
  {name:"Cadeira Abdutora",youtubeUrl:"https://www.youtube.com/watch?v=XDHvXNlNukw"},
  {name:"Elevação Pélvica na Máquina",youtubeUrl:"https://www.youtube.com/watch?v=HTdhMUgIxvE"},
  {name:"Panturrilha no Leg Press",youtubeUrl:"https://www.youtube.com/watch?v=zt_CQ3vbT0A"},
  {name:"Tríceps Testa com Halteres",youtubeUrl:"https://www.youtube.com/watch?v=VakpIeaaeXA"},
  {name:"Tríceps Testa com Barra",youtubeUrl:"https://www.youtube.com/watch?v=d_KZxkY_0cM"},
  {name:"Face Pull no Cabo",youtubeUrl:"https://www.youtube.com/watch?v=kYMTJAx_dTM"},
  {name:"Alongamento de Flexores do Quadril (Meia-Ajoelhado)",youtubeUrl:"https://www.youtube.com/watch?v=efCi4JAMBkU"},
  {name:"Remada Baixa com Pegada Aberta",youtubeUrl:"https://www.youtube.com/watch?v=WlDzBepwYvw"},
  {name:"Prancha com Toque no Ombro",youtubeUrl:"https://www.youtube.com/watch?v=xdyHJmuwO6w"},
  {name:"Corrida na Esteira",youtubeUrl:"https://www.youtube.com/watch?v=tiAB5rOUjCE"},
  {name:"Flexão de Braço Inclinada",youtubeUrl:"https://www.youtube.com/watch?v=tJTLOrZOh7w"},
  {name:"Dead Bug (Inseto Morto)",youtubeUrl:"https://www.youtube.com/watch?v=FC1Vg6ySKso"},
  {name:"Pressão de Peito com Faixa Elástica",youtubeUrl:"https://www.youtube.com/watch?v=vNCWSL31uw0"},
  {name:"Pullover com Halter",youtubeUrl:"https://www.youtube.com/watch?v=1hWxh0WI7lE"},
  {name:"Pull-over na Polia Alta",youtubeUrl:"https://www.youtube.com/watch?v=F8SukAvJv-Q"},
  {name:"Cadeira Extensora Isométrica",youtubeUrl:"https://www.youtube.com/watch?v=Iyt-fRdZzHo"},
  {name:"Abdominal Remador",youtubeUrl:"https://www.youtube.com/watch?v=NpQILl1BaZw"},
  {name:"Peck Deck (Voador)",youtubeUrl:"https://www.youtube.com/watch?v=FwtqdGlRgig"},
  {name:"Elevação Lateral Curvado",youtubeUrl:"https://www.youtube.com/watch?v=Vk6OCPWIPNI"},
  {name:"Rosca Punho",youtubeUrl:"https://www.youtube.com/watch?v=QQCZ7XZsenM"},
  {name:"Passada com Halteres",youtubeUrl:"https://www.youtube.com/watch?v=ez6b6yqjccM"},
  {name:"Face Pull na Corda para Ombro",youtubeUrl:"https://www.youtube.com/watch?v=0PwGUhaQNXY"},
  {name:"Alongamento de Panturrilha na Parede",youtubeUrl:"https://www.youtube.com/watch?v=kc2glDjeNfQ"},
  {name:"Puxada Alta Aberta",youtubeUrl:"https://www.youtube.com/watch?v=94seKBQlxLk"},
  {name:"Puxada Triângulo Neutra",youtubeUrl:"https://www.youtube.com/watch?v=093htCVTlOE"},
  {name:"Alongamento de Ombro Cruzado",youtubeUrl:"https://www.youtube.com/watch?v=0BmhNwyg0hc"},
  {name:"Levantamento Terra Romeno",youtubeUrl:"https://www.youtube.com/watch?v=f_q8m9Oivd8"},
  {name:"Remada Curvada com Halteres",youtubeUrl:"https://www.youtube.com/watch?v=cCpzwQnWTdU"},
  {name:"Abdominal Infra no Solo",youtubeUrl:"https://www.youtube.com/watch?v=yZYmdfnVepM"},
  {name:"Flexão Diamante",youtubeUrl:"https://www.youtube.com/watch?v=PAauHMIhWKg"},
  {name:"Polichinelo (Jumping Jacks)",youtubeUrl:"https://www.youtube.com/watch?v=S2uqQ9zHZMc"},
  {name:"Agachamento Frontal",youtubeUrl:"https://www.youtube.com/watch?v=sENTOxchGr0"},
  {name:"Cadeira Extensora Unilateral",youtubeUrl:"https://www.youtube.com/watch?v=il8PFadgG1o"},
  {name:"Rosca Direta na Máquina Smith",youtubeUrl:"https://www.youtube.com/watch?v=mG2s_TqxCiE"},
  {name:"Supino Inclinado com Barra",youtubeUrl:"https://www.youtube.com/watch?v=oZjIQN0YMX0"},
  {name:"Tríceps Pulley Barra Reta",youtubeUrl:"https://www.youtube.com/watch?v=epdvLgj7XSY"},
  {name:"Passada Reversa com Halteres",youtubeUrl:"https://www.youtube.com/watch?v=GMVIakP2m70"},
  {name:"Puxada Frontal com Pegada Fechada",youtubeUrl:"https://www.youtube.com/watch?v=inNlwUIq08w"},
  {name:"Agachamento Goblet",youtubeUrl:"https://www.youtube.com/watch?v=w6jCt94KAZk"},
  {name:"Encolhimento com Halteres",youtubeUrl:"https://www.youtube.com/watch?v=rYyBAjehdx0"},
  {name:"Rosca 21",youtubeUrl:"https://www.youtube.com/watch?v=hOYXQxBmibs"},
  {name:"Leg Press 45",youtubeUrl:"https://www.youtube.com/watch?v=IZxyjW7MPJQ"},
  {name:"Crucifixo no Cabo Unilateral",youtubeUrl:"https://www.youtube.com/watch?v=kbkWySbNoXg"},
  {name:"Tríceps Francês com Halteres",youtubeUrl:"https://www.youtube.com/watch?v=3aRGwoIa9tI"},
  {name:"Hack Squat na Máquina",youtubeUrl:"https://www.youtube.com/watch?v=68gNuQNxV9k"},
  {name:"Rosca no Cabo",youtubeUrl:"https://www.youtube.com/watch?v=JOAp8ud1dw8"},
  {name:"Tríceps Corda na Polia Alta",youtubeUrl:"https://www.youtube.com/watch?v=7le1JRUUagM"},
  {name:"Crucifixo Inverso com Halteres",youtubeUrl:"https://www.youtube.com/watch?v=oOhqtQN4g0o"},
  {name:"Gato-Camelo (Mobilidade Lombar)",youtubeUrl:"https://www.youtube.com/watch?v=QoxSN4siCXA"},
  {name:"Rosca Direta com Barra",youtubeUrl:"https://www.youtube.com/watch?v=kwG2ipFRgfo"},
  {name:"Rosca Martelo no Cabo com Corda",youtubeUrl:"https://www.youtube.com/watch?v=GVMsv9kiRVo"},
  {name:"Desenvolvimento Arnold",youtubeUrl:"https://www.youtube.com/watch?v=FtT2dFnWXlI"},
  {name:"Tríceps Testa na Máquina Smith",youtubeUrl:"https://www.youtube.com/watch?v=dmLypIEccd4"},
  {name:"Crucifixo Inverso na Máquina",youtubeUrl:"https://www.youtube.com/watch?v=g-DRuRRVilc"},
  {name:"Tríceps Pulley com Corda",youtubeUrl:"https://www.youtube.com/watch?v=vB5OHsJ3EME"},
  {name:"Supino Fechado na Máquina Smith",youtubeUrl:"https://www.youtube.com/watch?v=tIKRG7Doa50"},
  {name:"Prancha com Elevação de Perna",youtubeUrl:"https://www.youtube.com/watch?v=CFPdqlV7XBc"},
  {name:"Tríceps Coice com Halter",youtubeUrl:"https://www.youtube.com/watch?v=dnyUwaA7Pok"},
  {name:"Desenvolvimento com Halteres Sentado",youtubeUrl:"https://www.youtube.com/watch?v=0uB7PH3oFVo"},
  {name:"Supino Reto com Barra",youtubeUrl:"https://www.youtube.com/watch?v=rT7DgCr-3pg"},
  {name:"Rotação Externa com Halter",youtubeUrl:"https://www.youtube.com/watch?v=Sp9APndXQyg"},
  {name:"Tríceps Coice no Cabo",youtubeUrl:"https://www.youtube.com/watch?v=Mgf3BBYWpRA"},
  {name:"Crossover no Cabo",youtubeUrl:"https://www.youtube.com/watch?v=taI4XduLpTk"},
  {name:"Pulldown com Braços Estendidos",youtubeUrl:"https://www.youtube.com/watch?v=3uIW1Wmc2_I"},
  {name:"Crucifixo Inclinado com Halteres",youtubeUrl:"https://www.youtube.com/watch?v=MEouME-ymto"},
  {name:"Alongamento de Isquiotibiais em Pé",youtubeUrl:"https://www.youtube.com/watch?v=PNQ3UvdFkjc"},
  {name:"Abdominal na Máquina",youtubeUrl:"https://www.youtube.com/watch?v=g12GDh6PaY8"},
  {name:"Supino Inclinado com Halteres",youtubeUrl:"https://www.youtube.com/watch?v=8iPEnn-ltC8"},
  {name:"Corrida Intervalada (Sprints)",youtubeUrl:"https://www.youtube.com/watch?v=CMvvGW161Q8"},
  {name:"Flexão com Pés Elevados",youtubeUrl:"https://www.youtube.com/watch?v=N47IWR4dQBk"},
  {name:"Rosca Concentrada",youtubeUrl:"https://www.youtube.com/watch?v=xlVDnVGn6CY"},
  {name:"Puxada Alta com Triângulo",youtubeUrl:"https://www.youtube.com/watch?v=EcSSXWyz3TU"},
  {name:"Burpees",youtubeUrl:"https://www.youtube.com/watch?v=ChNWqTWunj4"},
  {name:"Prancha com Rotação",youtubeUrl:"https://www.youtube.com/watch?v=4VPBlaDSw2s"},
  {name:"Desenvolvimento com Barra",youtubeUrl:"https://www.youtube.com/watch?v=66ApmhLk6-k"},
  {name:"Cadeira Flexora Sentado",youtubeUrl:"https://www.youtube.com/watch?v=BrVJvDECpWM"},
  {name:"Crucifixo Reto com Halteres",youtubeUrl:"https://www.youtube.com/watch?v=eozdVDA78K0"},
  {name:"Supino Fechado com Barra",youtubeUrl:"https://www.youtube.com/watch?v=qbAHln_Eazs"},
  {name:"Supino Declinado com Barra",youtubeUrl:"https://www.youtube.com/watch?v=lD3gAnNHTT0"},
  {name:"Rosca Scott na Máquina",youtubeUrl:"https://www.youtube.com/watch?v=90sG3CFTz4E"},
  {name:"Supino Inclinado na Máquina Smith",youtubeUrl:"https://www.youtube.com/watch?v=NETEiC4PGow"},
  {name:"Crossover Baixo no Cabo",youtubeUrl:"https://www.youtube.com/watch?v=stLHnBELj34"},
  {name:"Tríceps Banco com Peso",youtubeUrl:"https://www.youtube.com/watch?v=F0x0R3EJ2V8"},
  {name:"Afundo com Halteres",youtubeUrl:"https://www.youtube.com/watch?v=QOVaHwm-Q6U"},
  {name:"Desenvolvimento Militar em Pé",youtubeUrl:"https://www.youtube.com/watch?v=Wu7xPX_0OIc"},
  {name:"Afundo Caminhando com Barra",youtubeUrl:"https://www.youtube.com/watch?v=DtXhNt_zbaA"},
  {name:"Abdominal Canivete",youtubeUrl:"https://www.youtube.com/watch?v=w3yvbUmjmkA"},
  {name:"Agachamento Sumô com Halter",youtubeUrl:"https://www.youtube.com/watch?v=hISzOeaSUBI"},
  {name:"Rosca Martelo",youtubeUrl:"https://www.youtube.com/watch?v=zC3nLlEvin4"},
];

async function main() {
  let updated = 0;
  const notFound: string[] = [];
  for (const { name, youtubeUrl } of EXERCISE_VIDEOS) {
    const result = await prisma.exercise.updateMany({
      where: { name },
      data: { mediaType: "YOUTUBE", mediaUrl: youtubeUrl },
    });
    if (result.count > 0) {
      updated++;
    } else {
      notFound.push(name);
    }
  }
  console.log(updated + "/" + EXERCISE_VIDEOS.length + " exercicio(s) atualizado(s) com video do YouTube.");
  if (notFound.length > 0) {
    console.log("Aviso: nome(s) nao encontrado(s) no catalogo:", notFound);
  }
}

main()
  .catch((err) => {
    console.error(err);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
