-- CreateEnum
CREATE TYPE "Specialty" AS ENUM ('HIPERTROFIA', 'EMAGRECIMENTO', 'FORCA_POWERLIFTING', 'FUNCIONAL', 'REABILITACAO', 'TERCEIRA_IDADE', 'GESTANTES', 'CROSSFIT', 'CORRIDA_CARDIO', 'NUTRICAO_ESPORTIVA');

-- AlterTable
ALTER TABLE "users" ADD COLUMN     "city" TEXT,
ADD COLUMN     "state" TEXT,
ADD COLUMN     "specialties" "Specialty"[] DEFAULT ARRAY[]::"Specialty"[];
